import mongoose, { Schema } from 'mongoose'
const RideSchema = new Schema({
  riderId: { type: Schema.Types.ObjectId, ref: 'User' },
  riderName: String,
  riderPhone: String,
  driverId: { type: Schema.Types.ObjectId, ref: 'Driver' },
  driverName: String,
  driverPhone: String,
  pickupAddress: String,
  dropAddress: String,
  pickupLat: Number,
  pickupLng: Number,
  dropLat: Number,
  dropLng: Number,
  service: { type: String, enum: ['taxi', 'rental', 'outstation', 'delivery'], default: 'taxi' },
  vehicleType: String,
  status: { type: String, enum: ['pending', 'accepted', 'ongoing', 'completed', 'cancelled'], default: 'pending' },
  fare: Number,
  distance: Number,
  duration: Number,
  paymentMode: { type: String, enum: ['cash', 'wallet', 'online'], default: 'cash' },
  paymentStatus: { type: String, enum: ['pending', 'paid'], default: 'pending' },
  scheduledAt: Date,
  startedAt: Date,
  completedAt: Date,
  cancelledBy: String,
  cancellationReason: String,
  driverRating: Number,
  riderRating: Number,
  otp: String,
  zoneId: { type: Schema.Types.ObjectId, ref: 'Zone' },
}, { timestamps: true })
export default mongoose.models.Ride || mongoose.model('Ride', RideSchema)
